# Makefile.in generated by automake 1.11.4 from Makefile.am.
# Makefile.  Generated from Makefile.in by configure.

# Copyright (C) 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002,
# 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011 Free Software
# Foundation, Inc.
# This Makefile.in is free software; the Free Software Foundation
# gives unlimited permission to copy and/or distribute it,
# with or without modifications, as long as this notice is preserved.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY, to the extent permitted by law; without
# even the implied warranty of MERCHANTABILITY or FITNESS FOR A
# PARTICULAR PURPOSE.







am__make_dryrun = \
  { \
    am__dry=no; \
    case $$MAKEFLAGS in \
      *\\[\ \	]*) \
        echo 'am--echo: ; @echo "AM"  OK' | $(MAKE) -f - 2>/dev/null \
          | grep '^AM OK$$' >/dev/null || am__dry=yes;; \
      *) \
        for am__flg in $$MAKEFLAGS; do \
          case $$am__flg in \
            *=*|--*) ;; \
            *n*) am__dry=yes; break;; \
          esac; \
        done;; \
    esac; \
    test $$am__dry = yes; \
  }
pkgdatadir = $(datadir)/libcap_utils
pkgincludedir = $(includedir)/libcap_utils
pkglibdir = $(libdir)/libcap_utils
pkglibexecdir = $(libexecdir)/libcap_utils
am__cd = CDPATH="$${ZSH_VERSION+.}$(PATH_SEPARATOR)" && cd
install_sh_DATA = $(install_sh) -c -m 644
install_sh_PROGRAM = $(install_sh) -c
install_sh_SCRIPT = $(install_sh) -c
INSTALL_HEADER = $(INSTALL_DATA)
transform = $(program_transform_name)
NORMAL_INSTALL = :
PRE_INSTALL = :
POST_INSTALL = :
NORMAL_UNINSTALL = :
PRE_UNINSTALL = :
POST_UNINSTALL = :
build_triplet = i686-pc-linux-gnu
host_triplet = i686-pc-linux-gnu
bin_PROGRAMS = $(am__EXEEXT_1) $(am__EXEEXT_2) $(am__EXEEXT_3) \
	$(am__EXEEXT_4) $(am__EXEEXT_5)
am__append_1 = pcap2cap cap2pcap
am__append_2 = capinfo
am__append_3 = capdump
am__append_4 = man/capdump.1
am__append_5 = man/capdump.1
am__append_6 = capfilter capmarker
am__append_7 = man/capfilter.1 man/capmarker.1
am__append_8 = man/capfilter.1 man/capmarker.1
am__append_9 = capshow
am__append_10 = man/capshow.1
am__append_11 = man/capshow.1
TESTS = tests/disabled$(EXEEXT)
#TESTS = tests/filter_argv$(EXEEXT) \
#	tests/address$(EXEEXT) tests/endian$(EXEEXT) \
#	tests/timepico$(EXEEXT)
check_PROGRAMS = $(am__EXEEXT_6)
#am__append_12 = stream_pfring.c
am__append_13 = stream_ethernet.c
#am__append_14 = be64toh.c be64toh.h
subdir = .
DIST_COMMON = README $(am__configure_deps) $(nobase_include_HEADERS) \
	$(notrans_dist_man_MANS) $(srcdir)/Makefile.am \
	$(srcdir)/Makefile.in $(srcdir)/config.h.in \
	$(srcdir)/libcap_filter-0.7.pc.in \
	$(srcdir)/libcap_marc-0.7.pc.in \
	$(srcdir)/libcap_stream-0.7.pc.in \
	$(srcdir)/libcap_utils-0.7.pc.in \
	$(top_srcdir)/caputils/version.h.in $(top_srcdir)/configure \
	$(top_srcdir)/dist/deb-control.in COPYING ChangeLog NEWS \
	build-aux/config.guess build-aux/config.sub build-aux/depcomp \
	build-aux/install-sh build-aux/ltmain.sh build-aux/missing
ACLOCAL_M4 = $(top_srcdir)/aclocal.m4
am__aclocal_m4_deps = $(top_srcdir)/m4/ax_pfring.m4 \
	$(top_srcdir)/m4/cppunit.m4 $(top_srcdir)/m4/libtool.m4 \
	$(top_srcdir)/m4/ltoptions.m4 $(top_srcdir)/m4/ltsugar.m4 \
	$(top_srcdir)/m4/ltversion.m4 $(top_srcdir)/m4/lt~obsolete.m4 \
	$(top_srcdir)/m4/pcap.m4 $(top_srcdir)/configure.ac
am__configure_deps = $(am__aclocal_m4_deps) $(CONFIGURE_DEPENDENCIES) \
	$(ACLOCAL_M4)
am__CONFIG_DISTCLEAN_FILES = config.status config.cache config.log \
 configure.lineno config.status.lineno
mkinstalldirs = $(install_sh) -d
CONFIG_HEADER = config.h
CONFIG_CLEAN_FILES = libcap_filter-0.7.pc libcap_stream-0.7.pc \
	libcap_marc-0.7.pc libcap_utils-0.7.pc caputils/version.h \
	dist/deb-control
CONFIG_CLEAN_VPATH_FILES =
am__vpath_adj_setup = srcdirstrip=`echo "$(srcdir)" | sed 's|.|.|g'`;
am__vpath_adj = case $$p in \
    $(srcdir)/*) f=`echo "$$p" | sed "s|^$$srcdirstrip/||"`;; \
    *) f=$$p;; \
  esac;
am__strip_dir = f=`echo $$p | sed -e 's|^.*/||'`;
am__install_max = 40
am__nobase_strip_setup = \
  srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*|]/\\\\&/g'`
am__nobase_strip = \
  for p in $$list; do echo "$$p"; done | sed -e "s|$$srcdirstrip/||"
am__nobase_list = $(am__nobase_strip_setup); \
  for p in $$list; do echo "$$p $$p"; done | \
  sed "s| $$srcdirstrip/| |;"' / .*\//!s/ .*/ ./; s,\( .*\)/[^/]*$$,\1,' | \
  $(AWK) 'BEGIN { files["."] = "" } { files[$$2] = files[$$2] " " $$1; \
    if (++n[$$2] == $(am__install_max)) \
      { print $$2, files[$$2]; n[$$2] = 0; files[$$2] = "" } } \
    END { for (dir in files) print dir, files[dir] }'
am__base_list = \
  sed '$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;$$!N;s/\n/ /g' | \
  sed '$$!N;$$!N;$$!N;$$!N;s/\n/ /g'
am__uninstall_files_from_dir = { \
  test -z "$$files" \
    || { test ! -d "$$dir" && test ! -f "$$dir" && test ! -r "$$dir"; } \
    || { echo " ( cd '$$dir' && rm -f" $$files ")"; \
         $(am__cd) "$$dir" && rm -f $$files; }; \
  }
am__installdirs = "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" \
	"$(DESTDIR)$(man1dir)" "$(DESTDIR)$(man3dir)" \
	"$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"
LTLIBRARIES = $(lib_LTLIBRARIES)
libcap_filter_07_la_LIBADD =
am_libcap_filter_07_la_OBJECTS = createfilter.lo filter.lo
libcap_filter_07_la_OBJECTS = $(am_libcap_filter_07_la_OBJECTS)
AM_V_lt = $(am__v_lt_$(V))
am__v_lt_ = $(am__v_lt_$(AM_DEFAULT_VERBOSITY))
am__v_lt_0 = --silent
libcap_filter_07_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(AM_CFLAGS) $(CFLAGS) $(libcap_filter_07_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libcap_marc_07_la_LIBADD =
am_libcap_marc_07_la_OBJECTS = libcap_marc_07_la-marc.lo
libcap_marc_07_la_OBJECTS = $(am_libcap_marc_07_la_OBJECTS)
libcap_marc_07_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(libcap_marc_07_la_CFLAGS) $(CFLAGS) \
	$(libcap_marc_07_la_LDFLAGS) $(LDFLAGS) -o $@
libcap_stream_07_la_DEPENDENCIES = libcap_filter-07.la
am__libcap_stream_07_la_SOURCES_DIST = stream.c stream.h stream_file.c \
	stream_pfring.c stream_ethernet.c
#am__objects_1 = stream_pfring.lo
am__objects_2 = stream_ethernet.lo
am_libcap_stream_07_la_OBJECTS = stream.lo stream_file.lo \
	$(am__objects_1) $(am__objects_2)
libcap_stream_07_la_OBJECTS = $(am_libcap_stream_07_la_OBJECTS)
libcap_stream_07_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(AM_CFLAGS) $(CFLAGS) $(libcap_stream_07_la_LDFLAGS) \
	$(LDFLAGS) -o $@
libcap_utils_07_la_DEPENDENCIES = libcap_stream-07.la \
	libcap_filter-07.la libcap_marc-07.la
am__libcap_utils_07_la_SOURCES_DIST = caputils_int.h address.c error.c \
	log.c marker.c utils.c picotime.c be64toh.c be64toh.h
#am__objects_3 = be64toh.lo
am_libcap_utils_07_la_OBJECTS = address.lo error.lo log.lo marker.lo \
	utils.lo picotime.lo $(am__objects_3)
libcap_utils_07_la_OBJECTS = $(am_libcap_utils_07_la_OBJECTS)
libcap_utils_07_la_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CCLD) \
	$(AM_CFLAGS) $(CFLAGS) $(libcap_utils_07_la_LDFLAGS) \
	$(LDFLAGS) -o $@
am__EXEEXT_1 = pcap2cap$(EXEEXT) cap2pcap$(EXEEXT)
am__EXEEXT_2 = capinfo$(EXEEXT)
am__EXEEXT_3 = capdump$(EXEEXT)
am__EXEEXT_4 = capfilter$(EXEEXT) \
	capmarker$(EXEEXT)
am__EXEEXT_5 = capshow$(EXEEXT)
am__EXEEXT_6 = tests/disabled$(EXEEXT)
#am__EXEEXT_6 = tests/filter_argv$(EXEEXT) \
#	tests/address$(EXEEXT) tests/endian$(EXEEXT) \
#	tests/timepico$(EXEEXT)
PROGRAMS = $(bin_PROGRAMS)
cap2pcap_SOURCES = cap2pcap.c
cap2pcap_OBJECTS = cap2pcap.$(OBJEXT)
am__DEPENDENCIES_1 =
cap2pcap_DEPENDENCIES = libcap_utils-07.la libcap_filter-07.la \
	libcap_stream-07.la $(am__DEPENDENCIES_1)
capdump_SOURCES = capdump.c
capdump_OBJECTS = capdump.$(OBJEXT)
capdump_DEPENDENCIES = libcap_utils-07.la libcap_filter-07.la \
	libcap_stream-07.la
capfilter_SOURCES = capfilter.c
capfilter_OBJECTS = capfilter.$(OBJEXT)
capfilter_DEPENDENCIES = libcap_filter-07.la libcap_utils-07.la \
	libcap_stream-07.la
capinfo_SOURCES = capinfo.c
capinfo_OBJECTS = capinfo.$(OBJEXT)
capinfo_DEPENDENCIES = libcap_utils-07.la libcap_filter-07.la \
	libcap_stream-07.la
capmarker_SOURCES = capmarker.c
capmarker_OBJECTS = capmarker.$(OBJEXT)
capmarker_DEPENDENCIES =
capshow_SOURCES = capshow.c
capshow_OBJECTS = capshow.$(OBJEXT)
capshow_DEPENDENCIES = libcap_filter-07.la libcap_utils-07.la \
	libcap_stream-07.la
pcap2cap_SOURCES = pcap2cap.c
pcap2cap_OBJECTS = pcap2cap.$(OBJEXT)
pcap2cap_DEPENDENCIES = libcap_utils-07.la libcap_filter-07.la \
	libcap_stream-07.la $(am__DEPENDENCIES_1)
am__dirstamp = $(am__leading_dot)dirstamp
am_tests_address_OBJECTS = tests/tests_address-address.$(OBJEXT)
tests_address_OBJECTS = $(am_tests_address_OBJECTS)
tests_address_DEPENDENCIES = libcap_utils-07.la
tests_address_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(tests_address_CXXFLAGS) $(CXXFLAGS) $(tests_address_LDFLAGS) \
	$(LDFLAGS) -o $@
am_tests_disabled_OBJECTS = tests/disabled.$(OBJEXT)
tests_disabled_OBJECTS = $(am_tests_disabled_OBJECTS)
tests_disabled_LDADD = $(LDADD)
am_tests_endian_OBJECTS = tests/tests_endian-endian.$(OBJEXT) \
	tests_endian-be64toh.$(OBJEXT)
tests_endian_OBJECTS = $(am_tests_endian_OBJECTS)
tests_endian_DEPENDENCIES = libcap_utils-07.la
tests_endian_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(tests_endian_CXXFLAGS) \
	$(CXXFLAGS) $(tests_endian_LDFLAGS) $(LDFLAGS) -o $@
am_tests_filter_argv_OBJECTS =  \
	tests/tests_filter_argv-filter_argv.$(OBJEXT)
tests_filter_argv_OBJECTS = $(am_tests_filter_argv_OBJECTS)
tests_filter_argv_DEPENDENCIES = libcap_filter-07.la \
	libcap_utils-07.la
tests_filter_argv_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(tests_filter_argv_CXXFLAGS) $(CXXFLAGS) \
	$(tests_filter_argv_LDFLAGS) $(LDFLAGS) -o $@
am_tests_timepico_OBJECTS = tests/tests_timepico-timepico.$(OBJEXT)
tests_timepico_OBJECTS = $(am_tests_timepico_OBJECTS)
tests_timepico_DEPENDENCIES = libcap_utils-07.la
tests_timepico_LINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX \
	$(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=link $(CXXLD) \
	$(tests_timepico_CXXFLAGS) $(CXXFLAGS) \
	$(tests_timepico_LDFLAGS) $(LDFLAGS) -o $@
DEFAULT_INCLUDES = -I.
depcomp = $(SHELL) $(top_srcdir)/build-aux/depcomp
am__depfiles_maybe = depfiles
am__mv = mv -f
COMPILE = $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) \
	$(CPPFLAGS) $(AM_CFLAGS) $(CFLAGS)
LTCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CFLAGS) $(CFLAGS)
AM_V_CC = $(am__v_CC_$(V))
am__v_CC_ = $(am__v_CC_$(AM_DEFAULT_VERBOSITY))
am__v_CC_0 = @echo "  CC    " $@;
AM_V_at = $(am__v_at_$(V))
am__v_at_ = $(am__v_at_$(AM_DEFAULT_VERBOSITY))
am__v_at_0 = @
CCLD = $(CC)
LINK = $(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CCLD) $(AM_CFLAGS) $(CFLAGS) \
	$(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CCLD = $(am__v_CCLD_$(V))
am__v_CCLD_ = $(am__v_CCLD_$(AM_DEFAULT_VERBOSITY))
am__v_CCLD_0 = @echo "  CCLD  " $@;
CXXCOMPILE = $(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) \
	$(AM_CPPFLAGS) $(CPPFLAGS) $(AM_CXXFLAGS) $(CXXFLAGS)
LTCXXCOMPILE = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=compile $(CXX) $(DEFS) \
	$(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) \
	$(AM_CXXFLAGS) $(CXXFLAGS)
AM_V_CXX = $(am__v_CXX_$(V))
am__v_CXX_ = $(am__v_CXX_$(AM_DEFAULT_VERBOSITY))
am__v_CXX_0 = @echo "  CXX   " $@;
CXXLD = $(CXX)
CXXLINK = $(LIBTOOL) $(AM_V_lt) --tag=CXX $(AM_LIBTOOLFLAGS) \
	$(LIBTOOLFLAGS) --mode=link $(CXXLD) $(AM_CXXFLAGS) \
	$(CXXFLAGS) $(AM_LDFLAGS) $(LDFLAGS) -o $@
AM_V_CXXLD = $(am__v_CXXLD_$(V))
am__v_CXXLD_ = $(am__v_CXXLD_$(AM_DEFAULT_VERBOSITY))
am__v_CXXLD_0 = @echo "  CXXLD " $@;
AM_V_GEN = $(am__v_GEN_$(V))
am__v_GEN_ = $(am__v_GEN_$(AM_DEFAULT_VERBOSITY))
am__v_GEN_0 = @echo "  GEN   " $@;
SOURCES = $(libcap_filter_07_la_SOURCES) $(libcap_marc_07_la_SOURCES) \
	$(libcap_stream_07_la_SOURCES) $(libcap_utils_07_la_SOURCES) \
	cap2pcap.c capdump.c capfilter.c capinfo.c capmarker.c \
	capshow.c pcap2cap.c $(tests_address_SOURCES) \
	$(tests_disabled_SOURCES) $(tests_endian_SOURCES) \
	$(tests_filter_argv_SOURCES) $(tests_timepico_SOURCES)
DIST_SOURCES = $(libcap_filter_07_la_SOURCES) \
	$(libcap_marc_07_la_SOURCES) \
	$(am__libcap_stream_07_la_SOURCES_DIST) \
	$(am__libcap_utils_07_la_SOURCES_DIST) cap2pcap.c capdump.c \
	capfilter.c capinfo.c capmarker.c capshow.c pcap2cap.c \
	$(tests_address_SOURCES) $(tests_disabled_SOURCES) \
	$(tests_endian_SOURCES) $(tests_filter_argv_SOURCES) \
	$(tests_timepico_SOURCES)
am__can_run_installinfo = \
  case $$AM_UPDATE_INFO_DIR in \
    n|no|NO) false;; \
    *) (install-info --version) >/dev/null 2>&1;; \
  esac
man1dir = $(mandir)/man1
man3dir = $(mandir)/man3
NROFF = nroff
MANS = $(man1_MANS) $(man3_MANS) $(notrans_dist_man_MANS)
DATA = $(pkgconfig_DATA)
HEADERS = $(nobase_include_HEADERS)
ETAGS = etags
CTAGS = ctags
# If stdout is a non-dumb tty, use colors.  If test -t is not supported,
# then this fails; a conservative approach.  Of course do not redirect
# stdout here, just stderr.
am__tty_colors = \
red=; grn=; lgn=; blu=; std=; \
test "X$(AM_COLOR_TESTS)" != Xno \
&& test "X$$TERM" != Xdumb \
&& { test "X$(AM_COLOR_TESTS)" = Xalways || test -t 1 2>/dev/null; } \
&& { \
  red='[0;31m'; \
  grn='[0;32m'; \
  lgn='[1;32m'; \
  blu='[1;34m'; \
  std='[m'; \
}
DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
distdir = $(PACKAGE)-$(VERSION)
top_distdir = $(distdir)
am__remove_distdir = \
  if test -d "$(distdir)"; then \
    find "$(distdir)" -type d ! -perm -200 -exec chmod u+w {} ';' \
      && rm -rf "$(distdir)" \
      || { sleep 5 && rm -rf "$(distdir)"; }; \
  else :; fi
DIST_ARCHIVES = $(distdir).tar.gz
GZIP_ENV = --best
distuninstallcheck_listfiles = find . -type f -print
am__distuninstallcheck_listfiles = $(distuninstallcheck_listfiles) \
  | sed 's|^\./|$(prefix)/|' | grep -v '$(infodir)/dir$$'
distcleancheck_listfiles = find . -type f -print
ACLOCAL = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/missing --run aclocal-1.11
AMTAR = $${TAR-tar}
AM_DEFAULT_VERBOSITY = 0
AR = ar
ARCH = i386
AUTOCONF = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/missing --run autoconf
AUTOHEADER = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/missing --run autoheader
AUTOMAKE = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/missing --run automake-1.11
AWK = mawk
CC = gcc -std=gnu99
CCDEPMODE = depmode=gcc3
CFLAGS = -g -O2
CPP = gcc -std=gnu99 -E
CPPFLAGS = 
CPPUNIT_CFLAGS = 
CPPUNIT_CONFIG = no
CPPUNIT_LIBS = 
CXX = g++
CXXCPP = g++ -E
CXXDEPMODE = depmode=gcc3
CXXFLAGS = -g -O2
CYGPATH_W = echo
DEFS = -DHAVE_CONFIG_H
DEPDIR = .deps
DLLTOOL = false
DSYMUTIL = 
DUMPBIN = 
ECHO_C = 
ECHO_N = -n
ECHO_T = 
EGREP = /bin/grep -E
EXEEXT = 
FGREP = /bin/grep -F
GREP = /bin/grep
INSTALL = /usr/bin/install -c
INSTALL_DATA = ${INSTALL} -m 644
INSTALL_PROGRAM = ${INSTALL}
INSTALL_SCRIPT = ${INSTALL}
INSTALL_STRIP_PROGRAM = $(install_sh) -c -s
LD = /usr/bin/ld
LDFLAGS = 
LIBOBJS = 
LIBS = 
LIBTOOL = $(SHELL) $(top_builddir)/libtool
LIPO = 
LN_S = ln -s
LTLIBOBJS = 
MAKEINFO = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/missing --run makeinfo
MANIFEST_TOOL = :
MKDIR_P = /bin/mkdir -p
NM = /usr/bin/nm -B
NMEDIT = 
OBJDUMP = objdump
OBJEXT = o
OTOOL = 
OTOOL64 = 
PACKAGE = libcap_utils
PACKAGE_BUGREPORT = dsv@bth.se
PACKAGE_NAME = libcap_utils
PACKAGE_STRING = libcap_utils 0.7.8
PACKAGE_TARNAME = libcap_utils
PACKAGE_URL = 
PACKAGE_VERSION = 0.7.8
PATH_SEPARATOR = :
PCAP_CFLAGS = 
PCAP_LIBS = -lpcap
PFRING_CFLAGS = 
PFRING_LIBS = 
RANLIB = ranlib
SED = /bin/sed
SET_MAKE = 
SHELL = /bin/bash
STRIP = strip
VERSION = 0.7.8
VERSION_MAJOR = 0
VERSION_MICRO = 8
VERSION_MINOR = 7
abs_builddir = /usr/local/src/dpmi7/qod_libcap_utils-0.7.8
abs_srcdir = /usr/local/src/dpmi7/qod_libcap_utils-0.7.8
abs_top_builddir = /usr/local/src/dpmi7/qod_libcap_utils-0.7.8
abs_top_srcdir = /usr/local/src/dpmi7/qod_libcap_utils-0.7.8
ac_ct_AR = ar
ac_ct_CC = gcc
ac_ct_CXX = g++
ac_ct_DUMPBIN = 
am__include = include
am__leading_dot = .
am__quote = 
am__tar = $${TAR-tar} chof - "$$tardir"
am__untar = $${TAR-tar} xf -
bindir = ${exec_prefix}/bin
build = i686-pc-linux-gnu
build_alias = 
build_cpu = i686
build_os = linux-gnu
build_vendor = pc
builddir = .
datadir = ${datarootdir}
datarootdir = ${prefix}/share
docdir = ${datarootdir}/doc/${PACKAGE_TARNAME}
dvidir = ${docdir}
exec_prefix = ${prefix}
host = i686-pc-linux-gnu
host_alias = 
host_cpu = i686
host_os = linux-gnu
host_vendor = pc
htmldir = ${docdir}
includedir = ${prefix}/include
infodir = ${datarootdir}/info
install_sh = ${SHELL} /usr/local/src/dpmi7/qod_libcap_utils-0.7.8/build-aux/install-sh
libdir = ${exec_prefix}/lib
libexecdir = ${exec_prefix}/libexec
localedir = ${datarootdir}/locale
localstatedir = ${prefix}/var
mandir = ${datarootdir}/man
mkdir_p = /bin/mkdir -p
oldincludedir = /usr/include
pdfdir = ${docdir}
prefix = /usr/local
program_transform_name = s,x,x,
psdir = ${docdir}
sbindir = ${exec_prefix}/sbin
sharedstatedir = ${prefix}/com
srcdir = .
sysconfdir = ${prefix}/etc
target_alias = 
top_build_prefix = 
top_builddir = .
top_srcdir = .
ACLOCAL_AMFLAGS = -I m4
AM_CFLAGS = -Wall ${PCAP_CFLAGS} ${PFRING_CFLAGS}
lib_LTLIBRARIES = libcap_utils-07.la libcap_filter-07.la libcap_stream-07.la libcap_marc-07.la
man1_MANS = $(am__append_4) $(am__append_7) $(am__append_10)
man3_MANS = \
	man/libcaputils.3     \
	man/libcap_filter.3   \
	man/stream_read.3

notrans_dist_man_MANS = man/libcaputils.3 man/libcap_filter.3 \
	man/stream_read.3 $(am__append_5) $(am__append_8) \
	$(am__append_11)
nobase_include_HEADERS = \
	caputils/address.h  \
	caputils/picotime.h \
	caputils/file.h     \
	caputils/utils.h    \
	caputils/capture.h  \
	caputils/filter.h   \
	caputils/caputils.h \
	caputils/log.h      \
	caputils/stream.h   \
	caputils/marc.h     \
	caputils/marker.h   \
	caputils/version.h

pkgconfigdir = $(libdir)/pkgconfig
pkgconfig_DATA = libcap_stream-0.7.pc libcap_filter-0.7.pc libcap_utils-0.7.pc libcap_marc-0.7.pc
libcap_stream_07_la_LDFLAGS = -version-info 1:0:1 ${PFRING_LIBS}
libcap_stream_07_la_LIBADD = libcap_filter-07.la
libcap_stream_07_la_SOURCES = stream.c stream.h stream_file.c \
	$(am__append_12) $(am__append_13)
libcap_utils_07_la_LDFLAGS = -version-info 0:1:0
libcap_utils_07_la_LIBADD = libcap_stream-07.la libcap_filter-07.la libcap_marc-07.la
libcap_utils_07_la_SOURCES = caputils_int.h address.c error.c log.c \
	marker.c utils.c picotime.c $(am__append_14)

#	stream_udp.c \
#	stream_tcp.c \
#
libcap_filter_07_la_LDFLAGS = -version-info 0:1:0
libcap_filter_07_la_SOURCES = createfilter.c filter.c
libcap_marc_07_la_LDFLAGS = -shared -version-info 0:1:0
libcap_marc_07_la_CFLAGS = ${AM_CFLAGS} ${libcap_filter_CFLAGS}
libcap_marc_07_la_SOURCES = marc.c
pcap2cap_LDADD = libcap_utils-07.la libcap_filter-07.la libcap_stream-07.la ${PCAP_LIBS}
cap2pcap_LDADD = libcap_utils-07.la libcap_filter-07.la libcap_stream-07.la ${PCAP_LIBS}
capinfo_LDADD = libcap_utils-07.la libcap_filter-07.la libcap_stream-07.la
capdump_LDADD = libcap_utils-07.la libcap_filter-07.la libcap_stream-07.la
capfilter_LDADD = libcap_filter-07.la libcap_utils-07.la libcap_stream-07.la
capmarker_LDADD = 
capshow_LDADD = libcap_filter-07.la libcap_utils-07.la libcap_stream-07.la
tests_filter_argv_CXXFLAGS = ${AM_CFLAGS} $(CPPUNIT_CFLAGS)
tests_filter_argv_LDFLAGS = $(CPPUNIT_LIBS)
tests_filter_argv_LDADD = libcap_filter-07.la libcap_utils-07.la
tests_filter_argv_SOURCES = tests/filter_argv.cpp
tests_address_CXXFLAGS = ${AM_CFLAGS} $(CPPUNIT_CFLAGS)
tests_address_LDFLAGS = $(CPPUNIT_LIBS)
tests_address_LDADD = libcap_utils-07.la
tests_address_SOURCES = tests/address.cpp

# -Dfulhack is needed so libtool will become less confused about
# multiple objects of be64toh. By having different cflags it will
# rename the files.
tests_endian_CFLAGS = ${AM_CFLAGS} -Dfulhack
tests_endian_CXXFLAGS = ${AM_CFLAGS} $(CPPUNIT_CFLAGS)
tests_endian_LDFLAGS = $(CPPUNIT_LIBS)
tests_endian_LDADD = libcap_utils-07.la
tests_endian_SOURCES = tests/endian.cpp be64toh.c
tests_timepico_CXXFLAGS = ${AM_CFLAGS} $(CPPUNIT_CFLAGS)
tests_timepico_LDFLAGS = $(CPPUNIT_LIBS)
tests_timepico_LDADD = libcap_utils-07.la
tests_timepico_SOURCES = tests/timepico.cpp
tests_disabled_SOURCES = tests/disabled.cpp

#
# Relase related targets
#
debpkgname = libcap-utils_0.7.8_i386
releasedir = /var/marc/releases
all: config.h
	$(MAKE) $(AM_MAKEFLAGS) all-am

.SUFFIXES:
.SUFFIXES: .c .cpp .lo .o .obj
am--refresh: Makefile
	@:
$(srcdir)/Makefile.in:  $(srcdir)/Makefile.am  $(am__configure_deps)
	@for dep in $?; do \
	  case '$(am__configure_deps)' in \
	    *$$dep*) \
	      echo ' cd $(srcdir) && $(AUTOMAKE) --foreign'; \
	      $(am__cd) $(srcdir) && $(AUTOMAKE) --foreign \
		&& exit 0; \
	      exit 1;; \
	  esac; \
	done; \
	echo ' cd $(top_srcdir) && $(AUTOMAKE) --foreign Makefile'; \
	$(am__cd) $(top_srcdir) && \
	  $(AUTOMAKE) --foreign Makefile
.PRECIOUS: Makefile
Makefile: $(srcdir)/Makefile.in $(top_builddir)/config.status
	@case '$?' in \
	  *config.status*) \
	    echo ' $(SHELL) ./config.status'; \
	    $(SHELL) ./config.status;; \
	  *) \
	    echo ' cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe)'; \
	    cd $(top_builddir) && $(SHELL) ./config.status $@ $(am__depfiles_maybe);; \
	esac;

$(top_builddir)/config.status: $(top_srcdir)/configure $(CONFIG_STATUS_DEPENDENCIES)
	$(SHELL) ./config.status --recheck

$(top_srcdir)/configure:  $(am__configure_deps)
	$(am__cd) $(srcdir) && $(AUTOCONF)
$(ACLOCAL_M4):  $(am__aclocal_m4_deps)
	$(am__cd) $(srcdir) && $(ACLOCAL) $(ACLOCAL_AMFLAGS)
$(am__aclocal_m4_deps):

config.h: stamp-h1
	@if test ! -f $@; then rm -f stamp-h1; else :; fi
	@if test ! -f $@; then $(MAKE) $(AM_MAKEFLAGS) stamp-h1; else :; fi

stamp-h1: $(srcdir)/config.h.in $(top_builddir)/config.status
	@rm -f stamp-h1
	cd $(top_builddir) && $(SHELL) ./config.status config.h
$(srcdir)/config.h.in:  $(am__configure_deps) 
	($(am__cd) $(top_srcdir) && $(AUTOHEADER))
	rm -f stamp-h1
	touch $@

distclean-hdr:
	-rm -f config.h stamp-h1
libcap_filter-0.7.pc: $(top_builddir)/config.status $(srcdir)/libcap_filter-0.7.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
libcap_stream-0.7.pc: $(top_builddir)/config.status $(srcdir)/libcap_stream-0.7.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
libcap_marc-0.7.pc: $(top_builddir)/config.status $(srcdir)/libcap_marc-0.7.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
libcap_utils-0.7.pc: $(top_builddir)/config.status $(srcdir)/libcap_utils-0.7.pc.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
caputils/version.h: $(top_builddir)/config.status $(top_srcdir)/caputils/version.h.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
dist/deb-control: $(top_builddir)/config.status $(top_srcdir)/dist/deb-control.in
	cd $(top_builddir) && $(SHELL) ./config.status $@
install-libLTLIBRARIES: $(lib_LTLIBRARIES)
	@$(NORMAL_INSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	list2=; for p in $$list; do \
	  if test -f $$p; then \
	    list2="$$list2 $$p"; \
	  else :; fi; \
	done; \
	test -z "$$list2" || { \
	  echo " $(MKDIR_P) '$(DESTDIR)$(libdir)'"; \
	  $(MKDIR_P) '$(DESTDIR)$(libdir)' || exit 1; \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 '$(DESTDIR)$(libdir)'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL) $(INSTALL_STRIP_FLAG) $$list2 "$(DESTDIR)$(libdir)"; \
	}

uninstall-libLTLIBRARIES:
	@$(NORMAL_UNINSTALL)
	@list='$(lib_LTLIBRARIES)'; test -n "$(libdir)" || list=; \
	for p in $$list; do \
	  $(am__strip_dir) \
	  echo " $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f '$(DESTDIR)$(libdir)/$$f'"; \
	  $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=uninstall rm -f "$(DESTDIR)$(libdir)/$$f"; \
	done

clean-libLTLIBRARIES:
	-test -z "$(lib_LTLIBRARIES)" || rm -f $(lib_LTLIBRARIES)
	@list='$(lib_LTLIBRARIES)'; for p in $$list; do \
	  dir="`echo $$p | sed -e 's|/[^/]*$$||'`"; \
	  test "$$dir" != "$$p" || dir=.; \
	  echo "rm -f \"$${dir}/so_locations\""; \
	  rm -f "$${dir}/so_locations"; \
	done
libcap_filter-07.la: $(libcap_filter_07_la_OBJECTS) $(libcap_filter_07_la_DEPENDENCIES) $(EXTRA_libcap_filter_07_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcap_filter_07_la_LINK) -rpath $(libdir) $(libcap_filter_07_la_OBJECTS) $(libcap_filter_07_la_LIBADD) $(LIBS)
libcap_marc-07.la: $(libcap_marc_07_la_OBJECTS) $(libcap_marc_07_la_DEPENDENCIES) $(EXTRA_libcap_marc_07_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcap_marc_07_la_LINK) -rpath $(libdir) $(libcap_marc_07_la_OBJECTS) $(libcap_marc_07_la_LIBADD) $(LIBS)
libcap_stream-07.la: $(libcap_stream_07_la_OBJECTS) $(libcap_stream_07_la_DEPENDENCIES) $(EXTRA_libcap_stream_07_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcap_stream_07_la_LINK) -rpath $(libdir) $(libcap_stream_07_la_OBJECTS) $(libcap_stream_07_la_LIBADD) $(LIBS)
libcap_utils-07.la: $(libcap_utils_07_la_OBJECTS) $(libcap_utils_07_la_DEPENDENCIES) $(EXTRA_libcap_utils_07_la_DEPENDENCIES) 
	$(AM_V_CCLD)$(libcap_utils_07_la_LINK) -rpath $(libdir) $(libcap_utils_07_la_OBJECTS) $(libcap_utils_07_la_LIBADD) $(LIBS)
install-binPROGRAMS: $(bin_PROGRAMS)
	@$(NORMAL_INSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(bindir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(bindir)" || exit 1; \
	fi; \
	for p in $$list; do echo "$$p $$p"; done | \
	sed 's/$(EXEEXT)$$//' | \
	while read p p1; do if test -f $$p || test -f $$p1; \
	  then echo "$$p"; echo "$$p"; else :; fi; \
	done | \
	sed -e 'p;s,.*/,,;n;h' -e 's|.*|.|' \
	    -e 'p;x;s,.*/,,;s/$(EXEEXT)$$//;$(transform);s/$$/$(EXEEXT)/' | \
	sed 'N;N;N;s,\n, ,g' | \
	$(AWK) 'BEGIN { files["."] = ""; dirs["."] = 1 } \
	  { d=$$3; if (dirs[d] != 1) { print "d", d; dirs[d] = 1 } \
	    if ($$2 == $$4) files[d] = files[d] " " $$1; \
	    else { print "f", $$3 "/" $$4, $$1; } } \
	  END { for (d in files) print "f", d, files[d] }' | \
	while read type dir files; do \
	    if test "$$dir" = .; then dir=; else dir=/$$dir; fi; \
	    test -z "$$files" || { \
	    echo " $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files '$(DESTDIR)$(bindir)$$dir'"; \
	    $(INSTALL_PROGRAM_ENV) $(LIBTOOL) $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=install $(INSTALL_PROGRAM) $$files "$(DESTDIR)$(bindir)$$dir" || exit $$?; \
	    } \
	; done

uninstall-binPROGRAMS:
	@$(NORMAL_UNINSTALL)
	@list='$(bin_PROGRAMS)'; test -n "$(bindir)" || list=; \
	files=`for p in $$list; do echo "$$p"; done | \
	  sed -e 'h;s,^.*/,,;s/$(EXEEXT)$$//;$(transform)' \
	      -e 's/$$/$(EXEEXT)/' `; \
	test -n "$$list" || exit 0; \
	echo " ( cd '$(DESTDIR)$(bindir)' && rm -f" $$files ")"; \
	cd "$(DESTDIR)$(bindir)" && rm -f $$files

clean-binPROGRAMS:
	@list='$(bin_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list

clean-checkPROGRAMS:
	@list='$(check_PROGRAMS)'; test -n "$$list" || exit 0; \
	echo " rm -f" $$list; \
	rm -f $$list || exit $$?; \
	test -n "$(EXEEXT)" || exit 0; \
	list=`for p in $$list; do echo "$$p"; done | sed 's/$(EXEEXT)$$//'`; \
	echo " rm -f" $$list; \
	rm -f $$list
cap2pcap$(EXEEXT): $(cap2pcap_OBJECTS) $(cap2pcap_DEPENDENCIES) $(EXTRA_cap2pcap_DEPENDENCIES) 
	@rm -f cap2pcap$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(cap2pcap_OBJECTS) $(cap2pcap_LDADD) $(LIBS)
capdump$(EXEEXT): $(capdump_OBJECTS) $(capdump_DEPENDENCIES) $(EXTRA_capdump_DEPENDENCIES) 
	@rm -f capdump$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(capdump_OBJECTS) $(capdump_LDADD) $(LIBS)
capfilter$(EXEEXT): $(capfilter_OBJECTS) $(capfilter_DEPENDENCIES) $(EXTRA_capfilter_DEPENDENCIES) 
	@rm -f capfilter$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(capfilter_OBJECTS) $(capfilter_LDADD) $(LIBS)
capinfo$(EXEEXT): $(capinfo_OBJECTS) $(capinfo_DEPENDENCIES) $(EXTRA_capinfo_DEPENDENCIES) 
	@rm -f capinfo$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(capinfo_OBJECTS) $(capinfo_LDADD) $(LIBS)
capmarker$(EXEEXT): $(capmarker_OBJECTS) $(capmarker_DEPENDENCIES) $(EXTRA_capmarker_DEPENDENCIES) 
	@rm -f capmarker$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(capmarker_OBJECTS) $(capmarker_LDADD) $(LIBS)
capshow$(EXEEXT): $(capshow_OBJECTS) $(capshow_DEPENDENCIES) $(EXTRA_capshow_DEPENDENCIES) 
	@rm -f capshow$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(capshow_OBJECTS) $(capshow_LDADD) $(LIBS)
pcap2cap$(EXEEXT): $(pcap2cap_OBJECTS) $(pcap2cap_DEPENDENCIES) $(EXTRA_pcap2cap_DEPENDENCIES) 
	@rm -f pcap2cap$(EXEEXT)
	$(AM_V_CCLD)$(LINK) $(pcap2cap_OBJECTS) $(pcap2cap_LDADD) $(LIBS)
tests/$(am__dirstamp):
	@$(MKDIR_P) tests
	@: > tests/$(am__dirstamp)
tests/$(DEPDIR)/$(am__dirstamp):
	@$(MKDIR_P) tests/$(DEPDIR)
	@: > tests/$(DEPDIR)/$(am__dirstamp)
tests/tests_address-address.$(OBJEXT): tests/$(am__dirstamp) \
	tests/$(DEPDIR)/$(am__dirstamp)
tests/address$(EXEEXT): $(tests_address_OBJECTS) $(tests_address_DEPENDENCIES) $(EXTRA_tests_address_DEPENDENCIES) tests/$(am__dirstamp)
	@rm -f tests/address$(EXEEXT)
	$(AM_V_CXXLD)$(tests_address_LINK) $(tests_address_OBJECTS) $(tests_address_LDADD) $(LIBS)
tests/disabled.$(OBJEXT): tests/$(am__dirstamp) \
	tests/$(DEPDIR)/$(am__dirstamp)
tests/disabled$(EXEEXT): $(tests_disabled_OBJECTS) $(tests_disabled_DEPENDENCIES) $(EXTRA_tests_disabled_DEPENDENCIES) tests/$(am__dirstamp)
	@rm -f tests/disabled$(EXEEXT)
	$(AM_V_CXXLD)$(CXXLINK) $(tests_disabled_OBJECTS) $(tests_disabled_LDADD) $(LIBS)
tests/tests_endian-endian.$(OBJEXT): tests/$(am__dirstamp) \
	tests/$(DEPDIR)/$(am__dirstamp)
tests/endian$(EXEEXT): $(tests_endian_OBJECTS) $(tests_endian_DEPENDENCIES) $(EXTRA_tests_endian_DEPENDENCIES) tests/$(am__dirstamp)
	@rm -f tests/endian$(EXEEXT)
	$(AM_V_CXXLD)$(tests_endian_LINK) $(tests_endian_OBJECTS) $(tests_endian_LDADD) $(LIBS)
tests/tests_filter_argv-filter_argv.$(OBJEXT): tests/$(am__dirstamp) \
	tests/$(DEPDIR)/$(am__dirstamp)
tests/filter_argv$(EXEEXT): $(tests_filter_argv_OBJECTS) $(tests_filter_argv_DEPENDENCIES) $(EXTRA_tests_filter_argv_DEPENDENCIES) tests/$(am__dirstamp)
	@rm -f tests/filter_argv$(EXEEXT)
	$(AM_V_CXXLD)$(tests_filter_argv_LINK) $(tests_filter_argv_OBJECTS) $(tests_filter_argv_LDADD) $(LIBS)
tests/tests_timepico-timepico.$(OBJEXT): tests/$(am__dirstamp) \
	tests/$(DEPDIR)/$(am__dirstamp)
tests/timepico$(EXEEXT): $(tests_timepico_OBJECTS) $(tests_timepico_DEPENDENCIES) $(EXTRA_tests_timepico_DEPENDENCIES) tests/$(am__dirstamp)
	@rm -f tests/timepico$(EXEEXT)
	$(AM_V_CXXLD)$(tests_timepico_LINK) $(tests_timepico_OBJECTS) $(tests_timepico_LDADD) $(LIBS)

mostlyclean-compile:
	-rm -f *.$(OBJEXT)
	-rm -f tests/disabled.$(OBJEXT)
	-rm -f tests/tests_address-address.$(OBJEXT)
	-rm -f tests/tests_endian-endian.$(OBJEXT)
	-rm -f tests/tests_filter_argv-filter_argv.$(OBJEXT)
	-rm -f tests/tests_timepico-timepico.$(OBJEXT)

distclean-compile:
	-rm -f *.tab.c

include ./$(DEPDIR)/address.Plo
include ./$(DEPDIR)/be64toh.Plo
include ./$(DEPDIR)/cap2pcap.Po
include ./$(DEPDIR)/capdump.Po
include ./$(DEPDIR)/capfilter.Po
include ./$(DEPDIR)/capinfo.Po
include ./$(DEPDIR)/capmarker.Po
include ./$(DEPDIR)/capshow.Po
include ./$(DEPDIR)/createfilter.Plo
include ./$(DEPDIR)/error.Plo
include ./$(DEPDIR)/filter.Plo
include ./$(DEPDIR)/libcap_marc_07_la-marc.Plo
include ./$(DEPDIR)/log.Plo
include ./$(DEPDIR)/marker.Plo
include ./$(DEPDIR)/pcap2cap.Po
include ./$(DEPDIR)/picotime.Plo
include ./$(DEPDIR)/stream.Plo
include ./$(DEPDIR)/stream_ethernet.Plo
include ./$(DEPDIR)/stream_file.Plo
include ./$(DEPDIR)/stream_pfring.Plo
include ./$(DEPDIR)/tests_endian-be64toh.Po
include ./$(DEPDIR)/utils.Plo
include tests/$(DEPDIR)/disabled.Po
include tests/$(DEPDIR)/tests_address-address.Po
include tests/$(DEPDIR)/tests_endian-endian.Po
include tests/$(DEPDIR)/tests_filter_argv-filter_argv.Po
include tests/$(DEPDIR)/tests_timepico-timepico.Po

.c.o:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ $<

.c.obj:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(COMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CC)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(COMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.c.lo:
	$(AM_V_CC)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CC)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LTCOMPILE) -c -o $@ $<

libcap_marc_07_la-marc.lo: marc.c
	$(AM_V_CC)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libcap_marc_07_la_CFLAGS) $(CFLAGS) -MT libcap_marc_07_la-marc.lo -MD -MP -MF $(DEPDIR)/libcap_marc_07_la-marc.Tpo -c -o libcap_marc_07_la-marc.lo `test -f 'marc.c' || echo '$(srcdir)/'`marc.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/libcap_marc_07_la-marc.Tpo $(DEPDIR)/libcap_marc_07_la-marc.Plo
#	$(AM_V_CC)source='marc.c' object='libcap_marc_07_la-marc.lo' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(LIBTOOL) $(AM_V_lt) --tag=CC $(AM_LIBTOOLFLAGS) $(LIBTOOLFLAGS) --mode=compile $(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(libcap_marc_07_la_CFLAGS) $(CFLAGS) -c -o libcap_marc_07_la-marc.lo `test -f 'marc.c' || echo '$(srcdir)/'`marc.c

tests_endian-be64toh.o: be64toh.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CFLAGS) $(CFLAGS) -MT tests_endian-be64toh.o -MD -MP -MF $(DEPDIR)/tests_endian-be64toh.Tpo -c -o tests_endian-be64toh.o `test -f 'be64toh.c' || echo '$(srcdir)/'`be64toh.c
	$(AM_V_at)$(am__mv) $(DEPDIR)/tests_endian-be64toh.Tpo $(DEPDIR)/tests_endian-be64toh.Po
#	$(AM_V_CC)source='be64toh.c' object='tests_endian-be64toh.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CFLAGS) $(CFLAGS) -c -o tests_endian-be64toh.o `test -f 'be64toh.c' || echo '$(srcdir)/'`be64toh.c

tests_endian-be64toh.obj: be64toh.c
	$(AM_V_CC)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CFLAGS) $(CFLAGS) -MT tests_endian-be64toh.obj -MD -MP -MF $(DEPDIR)/tests_endian-be64toh.Tpo -c -o tests_endian-be64toh.obj `if test -f 'be64toh.c'; then $(CYGPATH_W) 'be64toh.c'; else $(CYGPATH_W) '$(srcdir)/be64toh.c'; fi`
	$(AM_V_at)$(am__mv) $(DEPDIR)/tests_endian-be64toh.Tpo $(DEPDIR)/tests_endian-be64toh.Po
#	$(AM_V_CC)source='be64toh.c' object='tests_endian-be64toh.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CCDEPMODE) $(depcomp) \
#	$(AM_V_CC_no)$(CC) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CFLAGS) $(CFLAGS) -c -o tests_endian-be64toh.obj `if test -f 'be64toh.c'; then $(CYGPATH_W) 'be64toh.c'; else $(CYGPATH_W) '$(srcdir)/be64toh.c'; fi`

.cpp.o:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.o$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ $<

.cpp.obj:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.obj$$||'`;\
	$(CXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ `$(CYGPATH_W) '$<'` &&\
	$(am__mv) $$depbase.Tpo $$depbase.Po
#	$(AM_V_CXX)source='$<' object='$@' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXXCOMPILE) -c -o $@ `$(CYGPATH_W) '$<'`

.cpp.lo:
	$(AM_V_CXX)depbase=`echo $@ | sed 's|[^/]*$$|$(DEPDIR)/&|;s|\.lo$$||'`;\
	$(LTCXXCOMPILE) -MT $@ -MD -MP -MF $$depbase.Tpo -c -o $@ $< &&\
	$(am__mv) $$depbase.Tpo $$depbase.Plo
#	$(AM_V_CXX)source='$<' object='$@' libtool=yes \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(LTCXXCOMPILE) -c -o $@ $<

tests/tests_address-address.o: tests/address.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_address_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_address-address.o -MD -MP -MF tests/$(DEPDIR)/tests_address-address.Tpo -c -o tests/tests_address-address.o `test -f 'tests/address.cpp' || echo '$(srcdir)/'`tests/address.cpp
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_address-address.Tpo tests/$(DEPDIR)/tests_address-address.Po
#	$(AM_V_CXX)source='tests/address.cpp' object='tests/tests_address-address.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_address_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_address-address.o `test -f 'tests/address.cpp' || echo '$(srcdir)/'`tests/address.cpp

tests/tests_address-address.obj: tests/address.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_address_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_address-address.obj -MD -MP -MF tests/$(DEPDIR)/tests_address-address.Tpo -c -o tests/tests_address-address.obj `if test -f 'tests/address.cpp'; then $(CYGPATH_W) 'tests/address.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/address.cpp'; fi`
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_address-address.Tpo tests/$(DEPDIR)/tests_address-address.Po
#	$(AM_V_CXX)source='tests/address.cpp' object='tests/tests_address-address.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_address_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_address-address.obj `if test -f 'tests/address.cpp'; then $(CYGPATH_W) 'tests/address.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/address.cpp'; fi`

tests/tests_endian-endian.o: tests/endian.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_endian-endian.o -MD -MP -MF tests/$(DEPDIR)/tests_endian-endian.Tpo -c -o tests/tests_endian-endian.o `test -f 'tests/endian.cpp' || echo '$(srcdir)/'`tests/endian.cpp
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_endian-endian.Tpo tests/$(DEPDIR)/tests_endian-endian.Po
#	$(AM_V_CXX)source='tests/endian.cpp' object='tests/tests_endian-endian.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_endian-endian.o `test -f 'tests/endian.cpp' || echo '$(srcdir)/'`tests/endian.cpp

tests/tests_endian-endian.obj: tests/endian.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_endian-endian.obj -MD -MP -MF tests/$(DEPDIR)/tests_endian-endian.Tpo -c -o tests/tests_endian-endian.obj `if test -f 'tests/endian.cpp'; then $(CYGPATH_W) 'tests/endian.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/endian.cpp'; fi`
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_endian-endian.Tpo tests/$(DEPDIR)/tests_endian-endian.Po
#	$(AM_V_CXX)source='tests/endian.cpp' object='tests/tests_endian-endian.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_endian_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_endian-endian.obj `if test -f 'tests/endian.cpp'; then $(CYGPATH_W) 'tests/endian.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/endian.cpp'; fi`

tests/tests_filter_argv-filter_argv.o: tests/filter_argv.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_filter_argv_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_filter_argv-filter_argv.o -MD -MP -MF tests/$(DEPDIR)/tests_filter_argv-filter_argv.Tpo -c -o tests/tests_filter_argv-filter_argv.o `test -f 'tests/filter_argv.cpp' || echo '$(srcdir)/'`tests/filter_argv.cpp
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_filter_argv-filter_argv.Tpo tests/$(DEPDIR)/tests_filter_argv-filter_argv.Po
#	$(AM_V_CXX)source='tests/filter_argv.cpp' object='tests/tests_filter_argv-filter_argv.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_filter_argv_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_filter_argv-filter_argv.o `test -f 'tests/filter_argv.cpp' || echo '$(srcdir)/'`tests/filter_argv.cpp

tests/tests_filter_argv-filter_argv.obj: tests/filter_argv.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_filter_argv_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_filter_argv-filter_argv.obj -MD -MP -MF tests/$(DEPDIR)/tests_filter_argv-filter_argv.Tpo -c -o tests/tests_filter_argv-filter_argv.obj `if test -f 'tests/filter_argv.cpp'; then $(CYGPATH_W) 'tests/filter_argv.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/filter_argv.cpp'; fi`
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_filter_argv-filter_argv.Tpo tests/$(DEPDIR)/tests_filter_argv-filter_argv.Po
#	$(AM_V_CXX)source='tests/filter_argv.cpp' object='tests/tests_filter_argv-filter_argv.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_filter_argv_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_filter_argv-filter_argv.obj `if test -f 'tests/filter_argv.cpp'; then $(CYGPATH_W) 'tests/filter_argv.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/filter_argv.cpp'; fi`

tests/tests_timepico-timepico.o: tests/timepico.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_timepico_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_timepico-timepico.o -MD -MP -MF tests/$(DEPDIR)/tests_timepico-timepico.Tpo -c -o tests/tests_timepico-timepico.o `test -f 'tests/timepico.cpp' || echo '$(srcdir)/'`tests/timepico.cpp
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_timepico-timepico.Tpo tests/$(DEPDIR)/tests_timepico-timepico.Po
#	$(AM_V_CXX)source='tests/timepico.cpp' object='tests/tests_timepico-timepico.o' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_timepico_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_timepico-timepico.o `test -f 'tests/timepico.cpp' || echo '$(srcdir)/'`tests/timepico.cpp

tests/tests_timepico-timepico.obj: tests/timepico.cpp
	$(AM_V_CXX)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_timepico_CXXFLAGS) $(CXXFLAGS) -MT tests/tests_timepico-timepico.obj -MD -MP -MF tests/$(DEPDIR)/tests_timepico-timepico.Tpo -c -o tests/tests_timepico-timepico.obj `if test -f 'tests/timepico.cpp'; then $(CYGPATH_W) 'tests/timepico.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/timepico.cpp'; fi`
	$(AM_V_at)$(am__mv) tests/$(DEPDIR)/tests_timepico-timepico.Tpo tests/$(DEPDIR)/tests_timepico-timepico.Po
#	$(AM_V_CXX)source='tests/timepico.cpp' object='tests/tests_timepico-timepico.obj' libtool=no \
#	DEPDIR=$(DEPDIR) $(CXXDEPMODE) $(depcomp) \
#	$(AM_V_CXX_no)$(CXX) $(DEFS) $(DEFAULT_INCLUDES) $(INCLUDES) $(AM_CPPFLAGS) $(CPPFLAGS) $(tests_timepico_CXXFLAGS) $(CXXFLAGS) -c -o tests/tests_timepico-timepico.obj `if test -f 'tests/timepico.cpp'; then $(CYGPATH_W) 'tests/timepico.cpp'; else $(CYGPATH_W) '$(srcdir)/tests/timepico.cpp'; fi`

mostlyclean-libtool:
	-rm -f *.lo

clean-libtool:
	-rm -rf .libs _libs
	-rm -rf tests/.libs tests/_libs

distclean-libtool:
	-rm -f libtool config.lt
install-man1: $(man1_MANS) $(notrans_dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(notrans_dist_man_MANS)'; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed 'n;s,.*/,,;p;s,\.[^1][0-9a-z]*$$,.1,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }
	@list1='$(man1_MANS)'; \
	list2=''; \
	test -n "$(man1dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man1dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man1dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.1[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man1dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man1dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man1dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man1dir)" || exit $$?; }; \
	done; }

uninstall-man1:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(notrans_dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.1[a-z]*$$/p'; \
	} | sed 's,.*/,,;s,\.[^1][0-9a-z]*$$,.1,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
	@list='$(man1_MANS)'; test -n "$(man1dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^1][0-9a-z]*$$,1,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man1dir)'; $(am__uninstall_files_from_dir)
install-man3: $(man3_MANS) $(notrans_dist_man_MANS)
	@$(NORMAL_INSTALL)
	@list1=''; \
	list2='$(notrans_dist_man_MANS)'; \
	test -n "$(man3dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man3dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man3dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.3[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed 'n;s,.*/,,;p;s,\.[^3][0-9a-z]*$$,.3,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man3dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man3dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man3dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man3dir)" || exit $$?; }; \
	done; }
	@list1='$(man3_MANS)'; \
	list2=''; \
	test -n "$(man3dir)" \
	  && test -n "`echo $$list1$$list2`" \
	  || exit 0; \
	echo " $(MKDIR_P) '$(DESTDIR)$(man3dir)'"; \
	$(MKDIR_P) "$(DESTDIR)$(man3dir)" || exit 1; \
	{ for i in $$list1; do echo "$$i"; done;  \
	if test -n "$$list2"; then \
	  for i in $$list2; do echo "$$i"; done \
	    | sed -n '/\.3[a-z]*$$/p'; \
	fi; \
	} | while read p; do \
	  if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; echo "$$p"; \
	done | \
	sed -e 'n;s,.*/,,;p;h;s,.*\.,,;s,^[^3][0-9a-z]*$$,3,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,' | \
	sed 'N;N;s,\n, ,g' | { \
	list=; while read file base inst; do \
	  if test "$$base" = "$$inst"; then list="$$list $$file"; else \
	    echo " $(INSTALL_DATA) '$$file' '$(DESTDIR)$(man3dir)/$$inst'"; \
	    $(INSTALL_DATA) "$$file" "$(DESTDIR)$(man3dir)/$$inst" || exit $$?; \
	  fi; \
	done; \
	for i in $$list; do echo "$$i"; done | $(am__base_list) | \
	while read files; do \
	  test -z "$$files" || { \
	    echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(man3dir)'"; \
	    $(INSTALL_DATA) $$files "$(DESTDIR)$(man3dir)" || exit $$?; }; \
	done; }

uninstall-man3:
	@$(NORMAL_UNINSTALL)
	@list=''; test -n "$(man3dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	l2='$(notrans_dist_man_MANS)'; for i in $$l2; do echo "$$i"; done | \
	  sed -n '/\.3[a-z]*$$/p'; \
	} | sed 's,.*/,,;s,\.[^3][0-9a-z]*$$,.3,'`; \
	dir='$(DESTDIR)$(man3dir)'; $(am__uninstall_files_from_dir)
	@list='$(man3_MANS)'; test -n "$(man3dir)" || exit 0; \
	files=`{ for i in $$list; do echo "$$i"; done; \
	} | sed -e 's,.*/,,;h;s,.*\.,,;s,^[^3][0-9a-z]*$$,3,;x' \
	      -e 's,\.[0-9a-z]*$$,,;$(transform);G;s,\n,.,'`; \
	dir='$(DESTDIR)$(man3dir)'; $(am__uninstall_files_from_dir)
install-pkgconfigDATA: $(pkgconfig_DATA)
	@$(NORMAL_INSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(MKDIR_P) '$(DESTDIR)$(pkgconfigdir)' || exit 1; \
	fi; \
	for p in $$list; do \
	  if test -f "$$p"; then d=; else d="$(srcdir)/"; fi; \
	  echo "$$d$$p"; \
	done | $(am__base_list) | \
	while read files; do \
	  echo " $(INSTALL_DATA) $$files '$(DESTDIR)$(pkgconfigdir)'"; \
	  $(INSTALL_DATA) $$files "$(DESTDIR)$(pkgconfigdir)" || exit $$?; \
	done

uninstall-pkgconfigDATA:
	@$(NORMAL_UNINSTALL)
	@list='$(pkgconfig_DATA)'; test -n "$(pkgconfigdir)" || list=; \
	files=`for p in $$list; do echo $$p; done | sed -e 's|^.*/||'`; \
	dir='$(DESTDIR)$(pkgconfigdir)'; $(am__uninstall_files_from_dir)
install-nobase_includeHEADERS: $(nobase_include_HEADERS)
	@$(NORMAL_INSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	if test -n "$$list"; then \
	  echo " $(MKDIR_P) '$(DESTDIR)$(includedir)'"; \
	  $(MKDIR_P) "$(DESTDIR)$(includedir)" || exit 1; \
	fi; \
	$(am__nobase_list) | while read dir files; do \
	  xfiles=; for file in $$files; do \
	    if test -f "$$file"; then xfiles="$$xfiles $$file"; \
	    else xfiles="$$xfiles $(srcdir)/$$file"; fi; done; \
	  test -z "$$xfiles" || { \
	    test "x$$dir" = x. || { \
	      echo " $(MKDIR_P) '$(DESTDIR)$(includedir)/$$dir'"; \
	      $(MKDIR_P) "$(DESTDIR)$(includedir)/$$dir"; }; \
	    echo " $(INSTALL_HEADER) $$xfiles '$(DESTDIR)$(includedir)/$$dir'"; \
	    $(INSTALL_HEADER) $$xfiles "$(DESTDIR)$(includedir)/$$dir" || exit $$?; }; \
	done

uninstall-nobase_includeHEADERS:
	@$(NORMAL_UNINSTALL)
	@list='$(nobase_include_HEADERS)'; test -n "$(includedir)" || list=; \
	$(am__nobase_strip_setup); files=`$(am__nobase_strip)`; \
	dir='$(DESTDIR)$(includedir)'; $(am__uninstall_files_from_dir)

ID: $(HEADERS) $(SOURCES) $(LISP) $(TAGS_FILES)
	list='$(SOURCES) $(HEADERS) $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	mkid -fID $$unique
tags: TAGS

TAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	set x; \
	here=`pwd`; \
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	shift; \
	if test -z "$(ETAGS_ARGS)$$*$$unique"; then :; else \
	  test -n "$$unique" || unique=$$empty_fix; \
	  if test $$# -gt 0; then \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      "$$@" $$unique; \
	  else \
	    $(ETAGS) $(ETAGSFLAGS) $(AM_ETAGSFLAGS) $(ETAGS_ARGS) \
	      $$unique; \
	  fi; \
	fi
ctags: CTAGS
CTAGS:  $(HEADERS) $(SOURCES) config.h.in $(TAGS_DEPENDENCIES) \
		$(TAGS_FILES) $(LISP)
	list='$(SOURCES) $(HEADERS) config.h.in $(LISP) $(TAGS_FILES)'; \
	unique=`for i in $$list; do \
	    if test -f "$$i"; then echo $$i; else echo $(srcdir)/$$i; fi; \
	  done | \
	  $(AWK) '{ files[$$0] = 1; nonempty = 1; } \
	      END { if (nonempty) { for (i in files) print i; }; }'`; \
	test -z "$(CTAGS_ARGS)$$unique" \
	  || $(CTAGS) $(CTAGSFLAGS) $(AM_CTAGSFLAGS) $(CTAGS_ARGS) \
	     $$unique

GTAGS:
	here=`$(am__cd) $(top_builddir) && pwd` \
	  && $(am__cd) $(top_srcdir) \
	  && gtags -i $(GTAGS_ARGS) "$$here"

distclean-tags:
	-rm -f TAGS ID GTAGS GRTAGS GSYMS GPATH tags

check-TESTS: $(TESTS)
	@failed=0; all=0; xfail=0; xpass=0; skip=0; \
	srcdir=$(srcdir); export srcdir; \
	list=' $(TESTS) '; \
	$(am__tty_colors); \
	if test -n "$$list"; then \
	  for tst in $$list; do \
	    if test -f ./$$tst; then dir=./; \
	    elif test -f $$tst; then dir=; \
	    else dir="$(srcdir)/"; fi; \
	    if $(TESTS_ENVIRONMENT) $${dir}$$tst; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xpass=`expr $$xpass + 1`; \
		failed=`expr $$failed + 1`; \
		col=$$red; res=XPASS; \
	      ;; \
	      *) \
		col=$$grn; res=PASS; \
	      ;; \
	      esac; \
	    elif test $$? -ne 77; then \
	      all=`expr $$all + 1`; \
	      case " $(XFAIL_TESTS) " in \
	      *[\ \	]$$tst[\ \	]*) \
		xfail=`expr $$xfail + 1`; \
		col=$$lgn; res=XFAIL; \
	      ;; \
	      *) \
		failed=`expr $$failed + 1`; \
		col=$$red; res=FAIL; \
	      ;; \
	      esac; \
	    else \
	      skip=`expr $$skip + 1`; \
	      col=$$blu; res=SKIP; \
	    fi; \
	    echo "$${col}$$res$${std}: $$tst"; \
	  done; \
	  if test "$$all" -eq 1; then \
	    tests="test"; \
	    All=""; \
	  else \
	    tests="tests"; \
	    All="All "; \
	  fi; \
	  if test "$$failed" -eq 0; then \
	    if test "$$xfail" -eq 0; then \
	      banner="$$All$$all $$tests passed"; \
	    else \
	      if test "$$xfail" -eq 1; then failures=failure; else failures=failures; fi; \
	      banner="$$All$$all $$tests behaved as expected ($$xfail expected $$failures)"; \
	    fi; \
	  else \
	    if test "$$xpass" -eq 0; then \
	      banner="$$failed of $$all $$tests failed"; \
	    else \
	      if test "$$xpass" -eq 1; then passes=pass; else passes=passes; fi; \
	      banner="$$failed of $$all $$tests did not behave as expected ($$xpass unexpected $$passes)"; \
	    fi; \
	  fi; \
	  dashes="$$banner"; \
	  skipped=""; \
	  if test "$$skip" -ne 0; then \
	    if test "$$skip" -eq 1; then \
	      skipped="($$skip test was not run)"; \
	    else \
	      skipped="($$skip tests were not run)"; \
	    fi; \
	    test `echo "$$skipped" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$skipped"; \
	  fi; \
	  report=""; \
	  if test "$$failed" -ne 0 && test -n "$(PACKAGE_BUGREPORT)"; then \
	    report="Please report to $(PACKAGE_BUGREPORT)"; \
	    test `echo "$$report" | wc -c` -le `echo "$$banner" | wc -c` || \
	      dashes="$$report"; \
	  fi; \
	  dashes=`echo "$$dashes" | sed s/./=/g`; \
	  if test "$$failed" -eq 0; then \
	    col="$$grn"; \
	  else \
	    col="$$red"; \
	  fi; \
	  echo "$${col}$$dashes$${std}"; \
	  echo "$${col}$$banner$${std}"; \
	  test -z "$$skipped" || echo "$${col}$$skipped$${std}"; \
	  test -z "$$report" || echo "$${col}$$report$${std}"; \
	  echo "$${col}$$dashes$${std}"; \
	  test "$$failed" -eq 0; \
	else :; fi

distdir: $(DISTFILES)
	@case `sed 15q $(srcdir)/NEWS` in \
	*"$(VERSION)"*) : ;; \
	*) \
	  echo "NEWS not updated; not releasing" 1>&2; \
	  exit 1;; \
	esac
	@list='$(MANS)'; if test -n "$$list"; then \
	  list=`for p in $$list; do \
	    if test -f $$p; then d=; else d="$(srcdir)/"; fi; \
	    if test -f "$$d$$p"; then echo "$$d$$p"; else :; fi; done`; \
	  if test -n "$$list" && \
	    grep 'ab help2man is required to generate this page' $$list >/dev/null; then \
	    echo "error: found man pages containing the \`missing help2man' replacement text:" >&2; \
	    grep -l 'ab help2man is required to generate this page' $$list | sed 's/^/         /' >&2; \
	    echo "       to fix them, install help2man, remove and regenerate the man pages;" >&2; \
	    echo "       typically \`make maintainer-clean' will remove them" >&2; \
	    exit 1; \
	  else :; fi; \
	else :; fi
	$(am__remove_distdir)
	test -d "$(distdir)" || mkdir "$(distdir)"
	@srcdirstrip=`echo "$(srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	topsrcdirstrip=`echo "$(top_srcdir)" | sed 's/[].[^$$\\*]/\\\\&/g'`; \
	list='$(DISTFILES)'; \
	  dist_files=`for file in $$list; do echo $$file; done | \
	  sed -e "s|^$$srcdirstrip/||;t" \
	      -e "s|^$$topsrcdirstrip/|$(top_builddir)/|;t"`; \
	case $$dist_files in \
	  */*) $(MKDIR_P) `echo "$$dist_files" | \
			   sed '/\//!d;s|^|$(distdir)/|;s,/[^/]*$$,,' | \
			   sort -u` ;; \
	esac; \
	for file in $$dist_files; do \
	  if test -f $$file || test -d $$file; then d=.; else d=$(srcdir); fi; \
	  if test -d $$d/$$file; then \
	    dir=`echo "/$$file" | sed -e 's,/[^/]*$$,,'`; \
	    if test -d "$(distdir)/$$file"; then \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    if test -d $(srcdir)/$$file && test $$d != $(srcdir); then \
	      cp -fpR $(srcdir)/$$file "$(distdir)$$dir" || exit 1; \
	      find "$(distdir)/$$file" -type d ! -perm -700 -exec chmod u+rwx {} \;; \
	    fi; \
	    cp -fpR $$d/$$file "$(distdir)$$dir" || exit 1; \
	  else \
	    test -f "$(distdir)/$$file" \
	    || cp -p $$d/$$file "$(distdir)/$$file" \
	    || exit 1; \
	  fi; \
	done
	-test -n "$(am__skip_mode_fix)" \
	|| find "$(distdir)" -type d ! -perm -755 \
		-exec chmod u+rwx,go+rx {} \; -o \
	  ! -type d ! -perm -444 -links 1 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -400 -exec chmod a+r {} \; -o \
	  ! -type d ! -perm -444 -exec $(install_sh) -c -m a+r {} {} \; \
	|| chmod -R a+r "$(distdir)"
dist-gzip: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

dist-bzip2: distdir
	tardir=$(distdir) && $(am__tar) | BZIP2=$${BZIP2--9} bzip2 -c >$(distdir).tar.bz2
	$(am__remove_distdir)

dist-lzip: distdir
	tardir=$(distdir) && $(am__tar) | lzip -c $${LZIP_OPT--9} >$(distdir).tar.lz
	$(am__remove_distdir)

dist-lzma: distdir
	tardir=$(distdir) && $(am__tar) | lzma -9 -c >$(distdir).tar.lzma
	$(am__remove_distdir)

dist-xz: distdir
	tardir=$(distdir) && $(am__tar) | XZ_OPT=$${XZ_OPT--e} xz -c >$(distdir).tar.xz
	$(am__remove_distdir)

dist-tarZ: distdir
	tardir=$(distdir) && $(am__tar) | compress -c >$(distdir).tar.Z
	$(am__remove_distdir)

dist-shar: distdir
	shar $(distdir) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).shar.gz
	$(am__remove_distdir)

dist-zip: distdir
	-rm -f $(distdir).zip
	zip -rq $(distdir).zip $(distdir)
	$(am__remove_distdir)

dist dist-all: distdir
	tardir=$(distdir) && $(am__tar) | GZIP=$(GZIP_ENV) gzip -c >$(distdir).tar.gz
	$(am__remove_distdir)

# This target untars the dist file and tries a VPATH configuration.  Then
# it guarantees that the distribution is self-contained by making another
# tarfile.
distcheck: dist
	case '$(DIST_ARCHIVES)' in \
	*.tar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).tar.gz | $(am__untar) ;;\
	*.tar.bz2*) \
	  bzip2 -dc $(distdir).tar.bz2 | $(am__untar) ;;\
	*.tar.lzma*) \
	  lzma -dc $(distdir).tar.lzma | $(am__untar) ;;\
	*.tar.lz*) \
	  lzip -dc $(distdir).tar.lz | $(am__untar) ;;\
	*.tar.xz*) \
	  xz -dc $(distdir).tar.xz | $(am__untar) ;;\
	*.tar.Z*) \
	  uncompress -c $(distdir).tar.Z | $(am__untar) ;;\
	*.shar.gz*) \
	  GZIP=$(GZIP_ENV) gzip -dc $(distdir).shar.gz | unshar ;;\
	*.zip*) \
	  unzip $(distdir).zip ;;\
	esac
	chmod -R a-w $(distdir); chmod a+w $(distdir)
	mkdir $(distdir)/_build
	mkdir $(distdir)/_inst
	chmod a-w $(distdir)
	test -d $(distdir)/_build || exit 0; \
	dc_install_base=`$(am__cd) $(distdir)/_inst && pwd | sed -e 's,^[^:\\/]:[\\/],/,'` \
	  && dc_destdir="$${TMPDIR-/tmp}/am-dc-$$$$/" \
	  && am__cwd=`pwd` \
	  && $(am__cd) $(distdir)/_build \
	  && ../configure --srcdir=.. --prefix="$$dc_install_base" \
	    $(AM_DISTCHECK_CONFIGURE_FLAGS) \
	    $(DISTCHECK_CONFIGURE_FLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) \
	  && $(MAKE) $(AM_MAKEFLAGS) dvi \
	  && $(MAKE) $(AM_MAKEFLAGS) check \
	  && $(MAKE) $(AM_MAKEFLAGS) install \
	  && $(MAKE) $(AM_MAKEFLAGS) installcheck \
	  && $(MAKE) $(AM_MAKEFLAGS) uninstall \
	  && $(MAKE) $(AM_MAKEFLAGS) distuninstallcheck_dir="$$dc_install_base" \
	        distuninstallcheck \
	  && chmod -R a-w "$$dc_install_base" \
	  && ({ \
	       (cd ../.. && umask 077 && mkdir "$$dc_destdir") \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" install \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" uninstall \
	       && $(MAKE) $(AM_MAKEFLAGS) DESTDIR="$$dc_destdir" \
	            distuninstallcheck_dir="$$dc_destdir" distuninstallcheck; \
	      } || { rm -rf "$$dc_destdir"; exit 1; }) \
	  && rm -rf "$$dc_destdir" \
	  && $(MAKE) $(AM_MAKEFLAGS) dist \
	  && rm -rf $(DIST_ARCHIVES) \
	  && $(MAKE) $(AM_MAKEFLAGS) distcleancheck \
	  && cd "$$am__cwd" \
	  || exit 1
	$(am__remove_distdir)
	@(echo "$(distdir) archives ready for distribution: "; \
	  list='$(DIST_ARCHIVES)'; for i in $$list; do echo $$i; done) | \
	  sed -e 1h -e 1s/./=/g -e 1p -e 1x -e '$$p' -e '$$x'
distuninstallcheck:
	@test -n '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: trying to run $@ with an empty' \
	       '$$(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	$(am__cd) '$(distuninstallcheck_dir)' || { \
	  echo 'ERROR: cannot chdir into $(distuninstallcheck_dir)' >&2; \
	  exit 1; \
	}; \
	test `$(am__distuninstallcheck_listfiles) | wc -l` -eq 0 \
	   || { echo "ERROR: files left after uninstall:" ; \
	        if test -n "$(DESTDIR)"; then \
	          echo "  (check DESTDIR support)"; \
	        fi ; \
	        $(distuninstallcheck_listfiles) ; \
	        exit 1; } >&2
distcleancheck: distclean
	@if test '$(srcdir)' = . ; then \
	  echo "ERROR: distcleancheck can only run from a VPATH build" ; \
	  exit 1 ; \
	fi
	@test `$(distcleancheck_listfiles) | wc -l` -eq 0 \
	  || { echo "ERROR: files left in build directory after distclean:" ; \
	       $(distcleancheck_listfiles) ; \
	       exit 1; } >&2
check-am: all-am
	$(MAKE) $(AM_MAKEFLAGS) $(check_PROGRAMS)
	$(MAKE) $(AM_MAKEFLAGS) check-TESTS
check: check-am
all-am: Makefile $(LTLIBRARIES) $(PROGRAMS) $(MANS) $(DATA) $(HEADERS) \
		config.h
install-binPROGRAMS: install-libLTLIBRARIES

installdirs:
	for dir in "$(DESTDIR)$(libdir)" "$(DESTDIR)$(bindir)" "$(DESTDIR)$(man1dir)" "$(DESTDIR)$(man3dir)" "$(DESTDIR)$(pkgconfigdir)" "$(DESTDIR)$(includedir)"; do \
	  test -z "$$dir" || $(MKDIR_P) "$$dir"; \
	done
install: install-am
install-exec: install-exec-am
install-data: install-data-am
uninstall: uninstall-am

install-am: all-am
	@$(MAKE) $(AM_MAKEFLAGS) install-exec-am install-data-am

installcheck: installcheck-am
install-strip:
	if test -z '$(STRIP)'; then \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	      install; \
	else \
	  $(MAKE) $(AM_MAKEFLAGS) INSTALL_PROGRAM="$(INSTALL_STRIP_PROGRAM)" \
	    install_sh_PROGRAM="$(INSTALL_STRIP_PROGRAM)" INSTALL_STRIP_FLAG=-s \
	    "INSTALL_PROGRAM_ENV=STRIPPROG='$(STRIP)'" install; \
	fi
mostlyclean-generic:

clean-generic:

distclean-generic:
	-test -z "$(CONFIG_CLEAN_FILES)" || rm -f $(CONFIG_CLEAN_FILES)
	-test . = "$(srcdir)" || test -z "$(CONFIG_CLEAN_VPATH_FILES)" || rm -f $(CONFIG_CLEAN_VPATH_FILES)
	-rm -f tests/$(DEPDIR)/$(am__dirstamp)
	-rm -f tests/$(am__dirstamp)

maintainer-clean-generic:
	@echo "This command is intended for maintainers to use"
	@echo "it deletes files that may require special tools to rebuild."
#install-exec-hook:
clean: clean-am

clean-am: clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	clean-libLTLIBRARIES clean-libtool mostlyclean-am

distclean: distclean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf ./$(DEPDIR) tests/$(DEPDIR)
	-rm -f Makefile
distclean-am: clean-am distclean-compile distclean-generic \
	distclean-hdr distclean-libtool distclean-tags

dvi: dvi-am

dvi-am:

html: html-am

html-am:

info: info-am

info-am:

install-data-am: install-man install-nobase_includeHEADERS \
	install-pkgconfigDATA

install-dvi: install-dvi-am

install-dvi-am:

install-exec-am: install-binPROGRAMS install-libLTLIBRARIES
	@$(NORMAL_INSTALL)
	$(MAKE) $(AM_MAKEFLAGS) install-exec-hook
install-html: install-html-am

install-html-am:

install-info: install-info-am

install-info-am:

install-man: install-man1 install-man3

install-pdf: install-pdf-am

install-pdf-am:

install-ps: install-ps-am

install-ps-am:

installcheck-am:

maintainer-clean: maintainer-clean-am
	-rm -f $(am__CONFIG_DISTCLEAN_FILES)
	-rm -rf $(top_srcdir)/autom4te.cache
	-rm -rf ./$(DEPDIR) tests/$(DEPDIR)
	-rm -f Makefile
maintainer-clean-am: distclean-am maintainer-clean-generic

mostlyclean: mostlyclean-am

mostlyclean-am: mostlyclean-compile mostlyclean-generic \
	mostlyclean-libtool

pdf: pdf-am

pdf-am:

ps: ps-am

ps-am:

uninstall-am: uninstall-binPROGRAMS uninstall-libLTLIBRARIES \
	uninstall-man uninstall-nobase_includeHEADERS \
	uninstall-pkgconfigDATA

uninstall-man: uninstall-man1 uninstall-man3

.MAKE: all check-am install-am install-exec-am install-strip

.PHONY: CTAGS GTAGS all all-am am--refresh check check-TESTS check-am \
	clean clean-binPROGRAMS clean-checkPROGRAMS clean-generic \
	clean-libLTLIBRARIES clean-libtool ctags dist dist-all \
	dist-bzip2 dist-gzip dist-lzip dist-lzma dist-shar dist-tarZ \
	dist-xz dist-zip distcheck distclean distclean-compile \
	distclean-generic distclean-hdr distclean-libtool \
	distclean-tags distcleancheck distdir distuninstallcheck dvi \
	dvi-am html html-am info info-am install install-am \
	install-binPROGRAMS install-data install-data-am install-dvi \
	install-dvi-am install-exec install-exec-am install-exec-hook \
	install-html install-html-am install-info install-info-am \
	install-libLTLIBRARIES install-man install-man1 install-man3 \
	install-nobase_includeHEADERS install-pdf install-pdf-am \
	install-pkgconfigDATA install-ps install-ps-am install-strip \
	installcheck installcheck-am installdirs maintainer-clean \
	maintainer-clean-generic mostlyclean mostlyclean-compile \
	mostlyclean-generic mostlyclean-libtool pdf pdf-am ps ps-am \
	tags uninstall uninstall-am uninstall-binPROGRAMS \
	uninstall-libLTLIBRARIES uninstall-man uninstall-man1 \
	uninstall-man3 uninstall-nobase_includeHEADERS \
	uninstall-pkgconfigDATA


#
# Hooks
#

install-exec-hook:
	cd $(DESTDIR)$(bindir) && \
	  test -h consumer-ls$(EXEEXT) || $(LN_S) capshow$(EXEEXT) consumer-ls$(EXEEXT)

deb: all
	@test "x${prefix}" = "x/usr" || (echo "Error: --prefix must be /usr when creating debian release (currently ${prefix})"; exit 1)
	mkdir -p $(debpkgname)/DEBIAN
	cp dist/deb-control $(debpkgname)/DEBIAN/control
	$(MAKE) install DESTDIR=`pwd`/$(debpkgname)
	dpkg-deb --build $(debpkgname)

# special target for dsvmarc releases
release_marc: dist distcheck deb
	cp $(distdir).tar.gz $(releasedir)
	cp $(debpkgname).deb $(releasedir)
	cat $(top_srcdir)//ChangeLog | awk -vRS= '{print; if ( NR == 2 ){ exit }}' > $(releasedir)/$(distdir).changelog.txt

# Tell versions [3.59,3.63) of GNU make to not export all variables.
# Otherwise a system limit (for SysV at least) may be exceeded.
.NOEXPORT:
